<?php
/**
 * Apply image alt text updates generated by scripts/images/update-product-image-alt-text.py.
 *
 * Usage:
 *   wp eval-file scripts/php/apply-product-image-alt-updates.php /tmp/product-image-alt-updates.json --allow-root
 */

$file = $args[0] ?? '/tmp/product-image-alt-updates.json';
if (! file_exists($file)) {
    fwrite(STDERR, "Missing updates file: {$file}\n");
    exit(2);
}

$rows = json_decode(file_get_contents($file), true);
if (! is_array($rows)) {
    fwrite(STDERR, "Invalid JSON updates file: {$file}\n");
    exit(2);
}

$updated = 0;
$skipped = 0;
$failed = 0;

foreach ($rows as $row) {
    $media_id = isset($row['media_id']) ? (int) $row['media_id'] : 0;
    $alt = isset($row['new_alt']) ? trim((string) $row['new_alt']) : '';

    if ($media_id <= 0 || $alt === '') {
        $skipped++;
        continue;
    }

    if (get_post_type($media_id) !== 'attachment') {
        $failed++;
        continue;
    }

    update_post_meta($media_id, '_wp_attachment_image_alt', $alt);
    $updated++;
}

echo wp_json_encode([
    'updated' => $updated,
    'skipped' => $skipped,
    'failed' => $failed,
], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . PHP_EOL;
